config/routes.rb
Rails.application.routes.draw do

  resources :users do
    collection do
      get :search_friends
    end
  end

  resources :messages do
    collection do
      get :received_messages
      get :load_a_conversation

      post :delete_conversation, defaults: {format: :json}
      post :mark_as_read_unread, defaults: {format: :json}
    end
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :created_by, class_name: 'User', foreign_key: :created_by_id
  belongs_to :received_by, class_name: 'User', foreign_key: :received_by_id 

  has_many :users, through: :user_messages
  has_many :user_messages

  validates_presence_of :created_by_id, :received_by_id, :message

  scope :last_msg_on_conversation, -> {where("messages.id IN (SELECT MAX(messages.id) FROM messages GROUP BY message_code)").order(created_at: :desc)}

  scope :msgs_on_conversation, ->(msg_code) {where(message_code: msg_code)}

  before_save do
    self.message_code = Message.get_message_code(created_by_id, received_by_id)
  end

  after_create do
    self.user_messages.create({user_id: created_by_id, message_code: message_code, is_read: true, is_new: false})

    self.user_messages.create({user_id: received_by_id, message_code: message_code, is_read: false, is_new: true})
  end

  # Message code (conversation id) of messages from two people
  # 
  # @return [String] message code
  #
  # @author DatPB  
  def self.get_message_code(uid1, uid2)
    if uid1 <= uid2
      "#{uid1}-#{uid2}"
    else
      "#{uid2}-#{uid1}"
    end
  end

  # Load all conversations of a user
  # @param user [User] the User object
  # 
  # @return [Array] the array of conversations
  # .joins("LEFT JOIN user_messages ON messages.id = user_messages.message_id")
  # @author DatPB
  def self.load_conversations(user)
    #Message.includes([:created_by, :received_by]).where("received_by_id = ? OR created_by_id = ?", user.id, user.id)
    Message.includes([:created_by, :received_by]).last_msg_on_conversation.joins("LEFT JOIN user_messages ON messages.id = user_messages.message_id").where("user_messages.user_id = ? AND user_messages.is_deleted = ?", user.id, false).select("messages.*, user_messages.is_read, user_messages.is_new")
  end

  # Load a conversation of a user
  # @param user [User] the User object
  # @param friend [User] the User's friend object
  # @return [Array] the array of messages
  #
  # @author DatPB
  def self.load_conversation(user, friend)
    code = Message.get_message_code(user.id, friend.id)

    Message.where("messages.message_code = ?", code).joins("LEFT JOIN user_messages ON messages.id = user_messages.message_id").where("user_messages.user_id = ? AND user_messages.is_deleted = ?", user.id, false).select("messages.*, user_messages.is_read, user_messages.is_new").order(created_at: :desc)
  end

  # Load unread conversation of a user
  # @param user [User] the User object
  # @return [Array] the array of unread conversation
  #     (just user_messages collection, if you want to use message, you need add includes(:message))
  # @author DatPB
  def self.unread_conversation(user)
    user.user_messages.last_msg_on_conversation_of_user.where(is_read: false)
  end

  # Load new conversations of a user
  # @param user [User] the User object
  # @return [Array] the array of new conversations
  #     (just user_messages collection, if you want to use message, you need add includes(:message))
  # @author DatPB
  def self.new_conversation(user)
    user.user_messages.last_msg_on_conversation_of_user.where(is_new: true)
  end

  # Load new messages of a user
  # @param user [User] the User object
  # @return [Array] the array of new messages
  #     (just user_messages collection, if you want to use message, you need add includes(:message))
  # @author DatPB
  def self.new_messages(user)
    user.user_messages.where(is_new: true)
  end

  # Mark a conversation as read/unread ( we will mark the lastest received message of user)
  # @param user [User] the User object
  # @return [Hash] {success: true/false, new_status: read/unread, error_message: }
  #
  # @author DatPB
  def mark_as_read_unread!(user, type = "read")
    return_data = {success: true, new_status: type, error_message: ""}

    # if last_received_msg = Message.where({received_by_id: user.id, message_code: self.message_code}).order(created_at: :desc).first
    #   last_received_msg.is_read = (type == "read")
    #   last_received_msg.save

    #   return_data[:number_unread] = Message.unread(user.id).count
    # else
    #   return_data[:success] = false
    #   return_data[:new_status] = ((type == "read") ? "unread" : "read")
    # end
    begin
      is_read = (type == "read")
      user.user_messages.where("message_code = ? AND message_id <= ?", message_code, id).update_all(is_read: is_read)
      return_data[:number_unread] = Message.unread_conversation(user).count
    rescue Exception => e
      return_data[:success] = false
      return_data[:error_message] = e.message
    end

    return_data
  end

  # hide a conversation for user 
  # we will hide all older messages in this conversation, and this message for user
  # @param user [User] the User object
  # @return [Boolean] true/false 
  #
  # @author DatPB
  def delete_conversation(user)
    return_data = {success: true, error_message: ""}
    begin
      user.user_messages.where("message_code = ? AND message_id <= ?", message_code, id).update_all(is_deleted: true)
      return_data[:number_unread] = Message.unread_conversation(user).count
    rescue Exception => e
      return_data[:success] = false
      return_data[:error_message] = e.message
    end

    return_data
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!

  PER_PAGE = 10

  # GET /messages
  # GET /messages.json
  def index
    @messages = Message.load_conversations(current_user)
  end

  # GET /messages/load_a_conversation
  # GET /messages/load_a_conversation.json
  # for current user
  # @params:
  #  
  def load_a_conversation
    @last_timestamp = params[:last_timestamp].to_time rescue nil
    @per_page = 10
    
    if @friend = (User.find(params[:friend_id]) rescue nil)
      if @last_timestamp
        @messages = Message.load_conversation(current_user, @friend).where("messages.created_at < ? ", @last_timestamp).limit(@per_page)
      else
        @messages = Message.load_conversation(current_user, @friend).limit(@per_page)

        if first_msg = @messages.first
          first_msg.mark_as_read_unread!(current_user, "read")
        end
      end
    else 
      @messages = []
    end

    respond_to do |format|
      format.html { render :layout => false }
      format.json { render :layout => false }
    end
  end

  # GET /messages/received_messages
  # GET /messages/received_messages.json
  # for current user
  # @params:
  #  
  def received_messages
    @page = (params[:page] || 1).to_i rescue 1
    @messages = Message.load_conversations(current_user).paginate(page: @page, per_page: 2)
    if @page > 1
      @num_of_new = 0
    else
      @num_of_new = Message.new_conversation(current_user).count

      Message.new_messages(current_user).update_all(is_new: false)
    end

    respond_to do |format|
      format.html { render :layout => false}
      format.json {  }
    end
  end

  def mark_as_read_unread
    if @message = (Message.find(params[:message_id]) rescue nil)
      return_data = @message.mark_as_read_unread!(current_user, params[:type])

      respond_to do |format|
        format.html { redirect_to messages_url, notice: "Message was successfully mark as #{params[:type]}." }
        format.json { render :json => return_data }
      end
    else
      respond_to do |format|
        format.html { redirect_to messages_url, notice: 'Message is not found.' }
        format.json { render :json => {success: false, error_message: 'Message is not found.'} }
      end
    end
  end

  def delete_message
    if @message = (Message.find(params[:message_id]) rescue nil)
      #@message.destroy

      respond_to do |format|
        format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
        format.json { render :json => {success: true} }
      end
    else
      respond_to do |format|
        format.html { redirect_to messages_url, notice: 'Message is not found.' }
        format.json { render :json => {success: false} }
      end
    end
  end

  def delete_conversation
    if @message = (Message.find(params[:message_id]) rescue nil)
      @message.delete_conversation(current_user)

      respond_to do |format|
        format.html { redirect_to messages_url, notice: 'Conversation was successfully destroyed.' }
        format.json { render :json => {success: true} }
      end
    else
      respond_to do |format|
        format.html { redirect_to messages_url, notice: 'Conversation is not found.' }
        format.json { render :json => {success: false} }
      end
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = current_user.created_messages.new(message_params)

    respond_to do |format|
      if @message.save
        @new_messages = Message.load_conversation(current_user, @message.received_by).where("messages.created_at > ?", params[:last_timestamp].to_time)

        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :json => {
            new_messages_html: (render_to_string :partial => "messages/messages_in_chat_area", locals: {messages: @new_messages}, formats: [:html]),
            message: @message,
            new_messages: @new_messages,
            last_timestamp: Time.zone.now.advance({second: 1}),
            success: true
          } }
        format.js {}
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params[:message].permit(:message, :received_by_id)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
  def num_of_new_messages
    return 0 unless current_user

    Message.new_conversation(current_user).count
  end

  def num_of_unread_messages
    return 0 unless current_user

    Message.unread_conversation(current_user).count
  end

  def message_time(time)
    time_utc = time.utc
    current_time = Time.zone.now.utc

    if current_time.year == time_utc.year
      if current_time.beginning_of_day <= time_utc && time_utc <= current_time.end_of_day
        time.strftime("%I:%M%P")
      elsif current_time.beginning_of_week <= time_utc && time_utc <= current_time.end_of_week
        time.strftime("%a")
      else
        time.strftime("%b %d")
      end
    else
      time.strftime("%m/%d/%y")
    end
  end
end

app/views/messages/_chat_area.html.haml
- to ||= nil 
#chat-area{:'data-uid' => to.try(:id), :'data-user-name' => to.try(:user_name), :'data-last-timestamp' => Time.now}
  - if to
    .chat-room-head
      .pull-left
        %h4 #{to.full_name}
      .pull-right
        %button.btn.btn-primary#new-message New Message
  - else
    .chat-room-head
      %h4 New Message

    .new-to
      %span To:
      %input{type: :text, placeholder: "Name", role: "combobox", style: "width: 100%"}
  
  .messages-content
    %p.text-center.loading-icon
      %i.fa.fa-spinner
        Loading...
    - @messages.reverse.each do |msg|
      = render :partial => "message", locals: {message: msg}
 
  .msg-form-content
    = form_for Message.new, :remote => true do |f|
      = f.hidden_field :received_by_id, value: (to ? to.id : '')
      .msg-form-inner
        %textarea#message.message-form{:name => "message[message]", :placeholder => "Write a #{to ? 'reply' : 'message'}..."}
      %p#post-loader
        = image_tag "fb-loading.gif", class: "fb-loading-icon", width: "16", height: "11"
      .msg-btn{:name => "action", :type => "button", :value => "Post"}
        %span.press_enter Press Enter to send
        %input#press_to_enter{:checked => "checked", :name => "enter", :type => "checkbox", :value => "1"}
          %a#post_button.uibutton.large.confirm.btn.btn-primary Send

app/views/messages/_form.html.haml
= form_for @message do |f|
  - if @message.errors.any?
    #error_explanation
      %h2= "#{pluralize(@message.errors.count, "error")} prohibited this message from being saved:"
      %ul
        - @message.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/messages/_message.html.haml
.group-rom{:'data-created-at' => message.created_at}
  %div.photo.image-responsive
    = image_tag(message.created_by.get_avatar_url(:thumb), {:alt => "avatar"})
  %div.subject
    %a{href: user_path(message.created_by), target: "_blank"}
      %span.from #{message.created_by.full_name}
    
    %span.time 
      %i.fa.fa-clock-o
      #{message_time message.created_at}

    %span.message
      = message.message

app/views/messages/_messages_in_chat_area.html.haml
- messages ||= []
- messages.reverse.each do |msg|
  = render :partial => "message", locals: {message: msg}

app/views/messages/create.js.erb
<% if @message.valid? %>
  var message_div = '<div class="group-rom">'
                    +  '<div class="first-part"><%= @message.created_by.full_name %></div>'
                    +  '<div class="second-part"><%= @message.message %></div>'
                    +  '<div class="third-part"><%= message_time(@message.created_at) %></div>'
                    + '</div>';

  RallyFitMessage.main_side.find(".chat-area .messages-content").append($(message_div));

  RallyFitMessage.main_side.find(".chat-area #message").val("");
<% end %>

app/views/messages/edit.html.haml
%h1 Editing message

= render 'form'

= link_to 'Show', @message
\|
= link_to 'Back', messages_path

app/views/messages/index.html.haml
.container#rally
  .row
    .col-xs-12.col-sm-12.col-md-12
      
      / page start
      .chat-room.mt.messages-page
        .left-side.hidden-xs.col-sm-4.col-md-4
          .chat-room-head
            - if (num_of_unread = num_of_unread_messages) > 0
              %h4.pull-left.inbox-number-unread{:'data-num' => num_of_unread } Inbox (#{num_of_unread})
            - else
              %h4.pull-left.inbox-number-unread{:'data-num' => num_of_unread } Inbox

          .search-area
            %input#search_friend_on_conversations{type: :text, placeholder: "Search", role: "combobox"}
          
          %ul.conversations
            - @messages.each do |msg|
              - friend = msg.created_by
              - friend = msg.received_by if msg.created_by_id == current_user.id
              - is_read = (msg.is_read == 1)
              - status = is_read ? 'read' : 'unread'
              - new_status = is_read ? 'unread' : 'read'
              
              %li.received-message{:class => status, :'data-uid' => friend.id, :'data-page' => 0, :'data-name' => friend.full_name, :'data-email' => friend.email}
                %a{:href => "#"}
                  %div.photo.image-responsive
                    = image_tag(friend.get_avatar_url(:thumb), {:alt => "avatar"})
                  %div.subject
                    %span.from #{friend.full_name}
                    
                    %span.message
                      = msg.message

                    %span.time 
                      %i.fa.fa-clock-o
                      #{message_time msg.created_at}
                %div.action
                  %span.glyphicon.glyphicon-remove.remove-msg{:'data-uid' => msg.id, title: "Remove"}
                  %span.mark-as-read.fa{:class => (is_read ? "fa-circle-o" : "fa-check-circle-o" ),:'data-uid' => msg.id, title: "Mark as #{new_status}"}

        .main-side.col-xs-12.col-sm-8.col-md-8
          .chat-area
          
          .other-chat.non-display
      / page end

app/views/messages/load_a_conversation.html.haml
- if @last_timestamp.nil?
  = render :partial => "chat_area", locals: {to: @friend}
- else
  - @messages.reverse.each do |msg|
    = render :partial => "message", locals: {message: msg}

app/views/messages/new.html.haml
%h1 New message

= render 'form'

= link_to 'Back', messages_path

app/views/messages/received_messages.html.haml
- @messages.each do |msg|
  - friend = (msg.created_by_id != current_user.id) ? msg.created_by : msg.received_by
  - is_read = (msg.is_read == 1)
  - status = is_read ? 'read' : 'unread'
  - new_status = is_read ? 'unread' : 'read'
              
  %li.received-message{:class => status, :'data-uid' => friend.id, :'data-page' => 0, :'data-name' => friend.full_name, :'data-email' => friend.email}
    %a{:href => "#"}
      %div.photo.image-responsive
        = image_tag(friend.get_avatar_url(:thumb), {:alt => "avatar"})
      %div.subject
        %span.from #{friend.full_name}
        
        %span.message
          = msg.message
        %span.time 
          %i.fa.fa-clock-o
          #{message_time msg.created_at}
    %div.action
      %span.glyphicon.glyphicon-remove.remove-msg{:'data-uid' => msg.id, title: "Remove"}
      %span.mark-as-read.fa{:class => (is_read ? "fa-circle-o" : "fa-check-circle-o" ),:'data-uid' => msg.id, title: "Mark as #{new_status}"}

app/views/messages/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_message_path(@message)
\|
= link_to 'Back', messages_path